config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  get 'register', to: 'users#new'

  resources :articles
  
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum:1, maximum:50 }

  validates :body, presence: true, length: { minimum:1, maximum:2000 }

  validates :user_id , presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :articles

  before_save {self.email = email.downcase }

  validates :username , presence: true, length:{ minimum:3, maximum:20 },
    uniqueness: { case_sensitive: false }

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: { case_sensitive: false }, 
    length: { maximum:100 }, format: {with: VALID_EMAIL_REGEX}

  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  def index
    redirect_to articles_path if logged_in?
  end
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :get_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_owner, only: [:edit, :update, :destroy]
  def index
    @articles = Article.order('created_at DESC').paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      flash[:success] = "Article was successfully created!"
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted!"
    redirect_to articles_path 
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated!"
      redirect_to article_path(@article)
    else
      render :edit
    end
  end
  private
    def get_article
    @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title, :body)
    end
    def require_owner
      if current_user != @article.user
        flash[:danger] = "You can only modify your own articles"
        redirect_back fallback_location: root_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user  && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Login Success. Welcome #{User.find_by_email(params[:session][:email].downcase).username}"
      redirect_to root_path
    else
      flash.now[:danger] = "Invalid email/password"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_owner, only: [:edit, :update]
  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Registration success!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show 
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_owner
    if current_user != @user
      flash[:danger] = "Unauthorized access"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase);
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "profile-pic")
  end
end

app/views/application/index.html.erb
  <div class="jumbotron center">
    <h1 class="display-5">Simple Blog</h1>
    <hr class="my-4">
    <p>You must be logged in to post articles</p>
    <p class="lead">
    <div class="user-form-container">
    <div class="register-form">
      <%= form_for(:session, :html => {class: "form-horizontal", role: "form"}, url: login_path) do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
        </div>
      
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
        </div>
      
        <p>
          <%= f.submit "Login", class: "btn btn-primary btn-lg"  %>
        </p>
      <% end %>
    </div>
  </div>  
    </p>
    <%= link_to "Don't have an Account? Click here to register", register_path %>
  </div>

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="article-list-container">
  <div class="article-title">
    <%= link_to article.title, article_path(article) %>
    <div class="article-options">
      <% if logged_in? && current_user == article.user %>
        <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete", article_path(article), method: :delete, 
          data: { confirm: "Are you sure you want to delete the article?"}, 
          class: "btn btn-xs btn-danger" %>
      <% end %>
    </div>
    </div>
    <div class="article-body">
    <%= truncate(article.body, length: 100) %>
      <% if article.body.length >= 100 %>
        <%= link_to "Read all", article_path(article) %>
      <% end %>
    </div>
    <div class="article-footer">
    <div class="timestamp"> Last updated: <%= time_ago_in_words(article.updated_at) %> ago </div>
    <p>Created by: <%= link_to article.user.username, user_path(article.user) %> </p>
  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control", placeholder: "Body", rows: "10" %>
  </div>

  <p>
    <%= f.submit class: "btn btn-primary btn-lg"  %>
  </p>
  <p> <%= link_to "Back to articles", articles_path %> </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Update article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="article-index-container">
  <%= render 'article', obj: @articles %>
  <div class="paginate-container"> 
    <%= will_paginate %>
  </div>
</div>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
    <ul class="listing">
      <div class="center">
          <li>Created by: <%=@article.user.username%></li>
          <li class="article-title">
          </li>
          <li><small>
          </small></li>
      </div>
    </ul>
  <hr>
  <%= simple_format(@article.body) %>

  <div class="article-actions">
      <% if logged_in? && current_user == @article.user %>
        <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete", article_path(@article), method: :delete, 
          data: { confirm: "Are you sure you want to delete the article?"}, 
          class: "btn btn-xs btn-danger" %>
      <% end %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small blue">

  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="https://github.com/Thofeeq"> Thofeeq Mohamed </a>
  </div>

</footer>

app/views/layouts/_messages.html.erb
  <div class="container">
  <div class="col-xs-10 flash-message">
  <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
</div>

  </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom">

  <div class="navbar-left">
    <%= link_to 'Simple Blog', root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Articles" , articles_path, class: "nav-link" %>
        </li>
      </ul>
  </div>

  <div class="navbar-center">
    <form>
    <input class="form-control" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
  
  <div class="navbar-right">
    <% if logged_in? %>
      <div class="logged-in">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/articles/new"><i class="fas fa-plus"></i></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.username %>
            </a>
            <div class="dropdown-menu  dropdown-menu-right drop-ul" aria-labelledby="navbarDropdown">
             <%= link_to "My Profile", user_path(current_user), class: "dropdown-item drop-li" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item drop-li" %>
              <%= link_to "Logout", logout_path, method: :delete, class: "dropdown-item drop-li" %>
            </div>
          </li>
        </ul>
      </div>
    <% else %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/register">Register</a>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <div>
      <h4>
        Encountered <%= pluralize(obj.errors.count, "error") %>
      </h2>
    </div>
    <div>
      <ul>
      <%= obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="user-form-container">
  <div class="register-form">
    <%= form_for(@user) do |f| %>
        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, class: "form-control", placeholder: "Username" %>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
        </div>

        <p>
          <%= f.submit (@user.new_record? ? "Register" : "Update"), class: "btn btn-primary btn-lg"  %>
        </p>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="signup-form">
    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, class: "form-control col-sm-6", placeholder: "Username" %>
    </div>
  
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control col-sm-6", placeholder: "Email" %>
    </div>
  
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control col-sm-6", placeholder: "Password" %>
    </div>
  
    <p>
      <%= f.submit "Register", class: "btn btn-primary btn-lg"  %>
    </p>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="profile-page">
  <h2 align="center"> <%= @user.username %>'s Profile </h2>
  <div class="pic-container">
    <%= gravatar_for @user, 150 %>
  </div>
  <div id="article-counter">
    <p align="center"> Total articles posted: <strong> <%= @user.articles.count %> </strong></p>
    <% if @user.articles.count == 0 && current_user == @user%>  
      <%= link_to "Click here to post your first article!", new_article_path, align: "center" %>
    <% end %>
  </div>
  <div class="profile-page-articles">
    <%= render 'articles/article', obj: @user_articles %>
    <div class="paginate-container"> 
      <%= will_paginate @user_articles%>
    </div>
  </div>
</div>